### ISSUE TITLE
Configuring internal database with appliance_console fails

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-appliance_console#232]
```

Activating the configuration using the following settings...
Host:     localhost
Username: root
Database: vmdb_production
Region:   0

Initialize postgresql disk starting
Initialize postgresql disk complete
Initialize postgresql starting
Initialize postgresql complete
Configuration failed: Unknown alias: base

Press any key to continue.
```

I don't see anything interesting in the appliance_console.log
```
# cat log/appliance_console.log 
# Logfile created on 2024-02-01 14:31:10 -0500 by logger.rb/v1.5.0
I, [2024-02-01T14:31:10.224542 #6622]  INFO -- : MIQ(ManageIQ::ApplianceConsole::InternalDatabaseConfiguration#initialize_postgresql_disk) : starting
I, [2024-02-01T14:31:10.846971 #6622]  INFO -- : MIQ(ManageIQ::ApplianceConsole::InternalDatabaseConfiguration#initialize_postgresql_disk) : complete
I, [2024-02-01T14:31:10.855250 #6622]  INFO -- : MIQ(ManageIQ::ApplianceConsole::InternalDatabaseConfiguration#initialize_postgresql) : starting
I, [2024-02-01T14:31:12.887664 #6622]  INFO -- : MIQ(ManageIQ::ApplianceConsole::InternalDatabaseConfiguration#initialize_postgresql) : complete
```

But I'm pretty sure this is YAML safe_load related

**Comment by agrare** [comment]
cc @jrafanie

**Comment by agrare** [comment]
Ah, got the backtrace once I hit the any key
```
/opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:432:in `visit_Psych_Nodes_Alias': Unknown alias: base (Psych::BadAlias)
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:30:in `visit'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:6:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `each'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `each_slice'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `revive_hash'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:30:in `visit'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:6:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `each'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `each_slice'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:345:in `revive_hash'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:30:in `visit'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:6:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:320:in `visit_Psych_Nodes_Document'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:30:in `visit'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/visitor.rb:6:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych.rb:334:in `safe_load'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych.rb:369:in `load'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych.rb:671:in `block in load_file'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych.rb:670:in `open'
	from /opt/manageiq/manageiq-gemset/gems/psych-4.0.6/lib/psych.rb:670:in `load_file'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/lib/manageiq/appliance_console/database_configuration.rb:260:in `load_current'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/lib/manageiq/appliance_console/database_configuration.rb:203:in `current'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/lib/manageiq/appliance_console/database_configuration.rb:211:in `database_host'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/bin/appliance_console:104:in `block in <module:ApplianceConsole>'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/bin/appliance_console:89:in `loop'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/bin/appliance_console:89:in `<module:ApplianceConsole>'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/bin/appliance_console:80:in `<module:ManageIQ>'
	from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/bin/appliance_console:79:in `<top (required)>'
	from /opt/manageiq/manageiq-gemset/bin/appliance_console:25:in `load'
	from /opt/manageiq/manageiq-gemset/bin/appliance_console:25:in `<main>'
```

**Comment by agrare** [comment]
Confirmed switching `lib/manageiq/appliance_console/database_configuration.rb +260` to `YAML.unsafe_load_file` fixes the issue

**Comment by jrafanie** [comment]
yeah, `from /opt/manageiq/manageiq-gemset/gems/manageiq-appliance_console-8.0.0/lib/manageiq/appliance_console/database_configuration.rb:260:in `load_current'` needs to do `YAML.load(thing, :aliases => true)`

Probably like this:  https://github.com/ManageIQ/manageiq-appliance_console/pull/227/files
