### ISSUE TITLE
Setting replication using appliance_console_cli has error

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-appliance_console#28]
Hi

I am excited to know that we can use command line to set one of postgres as standby.
But the command was almost successful.

*  Both nodes show up as master after miqdb01(192.168.1.73) got shutdown and startup again.
```
[root@miqdb02 ~]#  su - postgres -c "repmgr cluster show"
[2018-01-07 21:07:45] [NOTICE] Redirecting logging output to '/var/log/repmgr/repmgrd.log'
Role      | Name             | Upstream     | Connection String
----------+------------------|--------------|-------------------------------------------------------
* master  | 192.168.1.73     |              | host=192.168.1.73 user=root dbname=vmdb_production
* master  | miqdb02.test.lan | 192.168.1.73 | host=miqdb02.test.lan user=root dbname=vmdb_production
[root@miqdb02 ~]#

```
* Via appliance_console text GUI is ok.
```
Replication Server Configuration

        Cluster Node Number:        2
        Cluster Database Name:      vmdb_production
        Cluster Database User:      root
        Cluster Database Password:  "********"
        Cluster Primary Host:       miqdb01.test.lan
        Standby Host:               miqdb02.test.lan
        Automatic Failover:         enabled
Apply this Replication Server Configuration? (Y/N): Y
Configuring Replication Standby Server...
<snipped>
```
* make sure both miqdb01/02 only has one connection like following
```
root@miqdb01 ~]#  netstat -antulp |grep 5432
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      3682/postgres
tcp6       0      0 :::5432                 :::*                    LISTEN      3682/postgres
[root@miqdb01 ~]#

```
* via following long command line is not.
Maybe I missed an option ?

```
[root@miqdb02 ~]# appliance_console_cli --hostname=miqdb02.test.lan --standby-host=miqdb02.test.lan  --username=root --password=smartvm --replication=standby --cluster-node-number=2 --auto-failover  --primary-host=miqdb01.test.lan --region=99
configuring external database
Checking for connections to the database...

Warning: There are 1 existing connections to the database preventing the setup of a database region.
Please stop the EVM server process on all appliances in the region.

Failed to configure external database
Configuring Server as Standby
Configuring Replication Standby Server...

[2018-01-07 20:52:28] [NOTICE] Redirecting logging output to '/var/log/repmgr/repmgrd.log'

Failed to configure replication server
/usr/local/lib/ruby/gems/2.3.0/gems/awesome_spawn-1.4.1/lib/awesome_spawn.rb:105:in `run!': repmgr exit code: 1 (AwesomeSpawn::CommandResultError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/database_replication.rb:122:in `block in run_repmgr_command'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/database_replication.rb:119:in `fork'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/database_replication.rb:119:in `run_repmgr_command'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/database_replication_standby.rb:96:in `clone_standby_server'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/database_replication_standby.rb:68:in `activate'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/cli.rb:270:in `set_replication'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/cli.rb:172:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/lib/manageiq/appliance_console/cli.rb:399:in `parse'
        from /usr/local/lib/ruby/gems/2.3.0/gems/manageiq-appliance_console-1.2.2/bin/appliance_console_cli:7:in `<top (required)>'
        from /usr/local/bin/appliance_console_cli:23:in `load'
        from /usr/local/bin/appliance_console_cli:23:in `<main>'
[root@miqdb02 ~]#

```

* log from miqdb02:/var/log/repmgr/repmgrd.log
```
[root@miqdb02 ~]# tail /var/log/repmgr/repmgrd.log
[2018-01-07 20:58:02] [WARNING] directory "/var/opt/rh/rh-postgresql95/lib/pgsql/data" exists but is not empty
[2018-01-07 20:58:02] [HINT] This looks like a PostgreSQL directory.
If you are sure you want to clone here, please check there is no PostgreSQL server running and use the -F/--force option
[2018-01-07 20:58:02] [ERROR] unable to use directory /var/opt/rh/rh-postgresql95/lib/pgsql/data ...
[2018-01-07 20:58:02] [HINT] use -F/--force option to force this directory to be overwritten
[2018-01-07 20:58:02] [ERROR] unable to drop replication slot "repmgr_slot_2":
 ERROR:  replication slot "repmgr_slot_2" does not exist

[2018-01-07 20:58:02] [ERROR] unable to take a base backup of the master server
[2018-01-07 20:58:02] [WARNING] destination directory (/var/opt/rh/rh-postgresql95/lib/pgsql/data) may need to be cleaned up manually
[root@miqdb02 ~]#


```

**Comment by carbonin** [comment]
Your console command line string isn't quite correct. To set a server up as a standby you would need this:

`appliance_console_cli --standby-host=miqdb02.test.lan  --username=root --password=smartvm --replication=standby --cluster-node-number=2 --auto-failover  --primary-host=miqdb01.test.lan`

Really I just removed the `--hostname` and `--region` arguments.

`--hostname` is the host of the external database you want to connect to when initializing the application regularly. `--region` tells the console that you want to create a region in the database on the specified host. You don't want to do either of these things here.

Additionally, you will have to make sure that the data directory is empty before configuring a standby server using the cli. We have an option to do this for you in the interactive console, but we figured it was safer to not delete the database automatically from the cli.

Can you try out the command from above with a clean data directory and see if that helps?

**Comment by tjyang** [comment]
Hi @carbonin 
Can you advise how can I empty standby(mqdb02) server's data directory ?
Is it as simple as this command 
```
rm -rf /var/opt/rh/rh-postgresql95/lib/pgsql/data
```

**Comment by carbonin** [comment]
I usually do something like this:

```bash
# Remove database
pushd $APPLIANCE_PG_DATA
  rm -rf ./*
popd
```

Taken from my [gist](https://gist.github.com/carbonin/a25b84efca2e6b3c3f91b673821a22c8) to clean up the initial database on an appliance

**Comment by tjyang** [comment]
Thanks for sharing your gist at https://gist.github.com/carbonin/a25b84efca2e6b3c3f91b673821a22c8
